"""add_is_timeless_to_courses_and_templates

Revision ID: 36dec64c7d56
Revises: 78b423698a32
Create Date: 2026-04-16 11:21:07.483931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dec64c7d56'
down_revision: Union[str, Sequence[str], None] = '78b423698a32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_timeless', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_timeless', sa.Boolean(), nullable=False, server_default='0'))

    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_room_building_number', ['building', 'room_number'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_constraint('uix_room_building_number', type_='unique')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('is_timeless')

    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.drop_column('is_timeless')

    # ### end Alembic commands ###
