"""initial_schema

Revision ID: 78b423698a32
Revises: 
Create Date: 2026-04-07 14:51:56.775784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78b423698a32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('constraints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_constraints_id'), ['id'], unique=False)

    op.create_table('course_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('default_min_sections', sa.Integer(), nullable=False),
    sa.Column('default_max_sections', sa.Integer(), nullable=False),
    sa.Column('default_capacity', sa.Integer(), nullable=False),
    sa.Column('core_ssc', sa.Boolean(), nullable=False),
    sa.Column('core_ht', sa.Boolean(), nullable=False),
    sa.Column('core_ga', sa.Boolean(), nullable=False),
    sa.Column('core_wem', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_templates_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_templates_id'), ['id'], unique=False)

    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tcu_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('office', sa.String(), nullable=True),
    sa.Column('rank', sa.String(), nullable=False),
    sa.Column('fall_count', sa.Integer(), nullable=False),
    sa.Column('spring_count', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_professors_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_professors_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_professors_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_professors_tcu_id'), ['tcu_id'], unique=True)

    op.create_table('rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('building', sa.String(), nullable=False),
    sa.Column('room_number', sa.String(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rooms_id'), ['id'], unique=False)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('solver_log', sa.String(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(), nullable=True),
    sa.Column('excel_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_id'), ['id'], unique=False)

    op.create_table('time_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('days', sa.String(), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('section_number', sa.String(), nullable=False),
    sa.Column('max_classes', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_slots_id'), ['id'], unique=False)

    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('min_sections', sa.Integer(), nullable=False),
    sa.Column('max_sections', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('core_ssc', sa.Boolean(), nullable=False),
    sa.Column('core_ht', sa.Boolean(), nullable=False),
    sa.Column('core_ga', sa.Boolean(), nullable=False),
    sa.Column('core_wem', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['course_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'name', 'semester', 'year', name='uix_course_code_name_term')
    )
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_courses_code'), ['code'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_semester'), ['semester'], unique=False)
        batch_op.create_index(batch_op.f('ix_courses_year'), ['year'], unique=False)

    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('direction', sa.String(), nullable=False),
    sa.Column('gmail_thread_id', sa.String(), nullable=True),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_log_id'), ['id'], unique=False)

    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('raw_email', sa.String(), nullable=True),
    sa.Column('parsed_json', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('admin_approved', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_preferences_id'), ['id'], unique=False)

    op.create_table('sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('timeslot_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['time_slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sections_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sections_id'))

    op.drop_table('sections')
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_preferences_id'))

    op.drop_table('preferences')
    with op.batch_alter_table('email_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_log_id'))

    op.drop_table('email_log')
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_year'))
        batch_op.drop_index(batch_op.f('ix_courses_semester'))
        batch_op.drop_index(batch_op.f('ix_courses_id'))
        batch_op.drop_index(batch_op.f('ix_courses_code'))

    op.drop_table('courses')
    with op.batch_alter_table('time_slots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_slots_id'))

    op.drop_table('time_slots')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('rooms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rooms_id'))

    op.drop_table('rooms')
    with op.batch_alter_table('professors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_professors_tcu_id'))
        batch_op.drop_index(batch_op.f('ix_professors_name'))
        batch_op.drop_index(batch_op.f('ix_professors_id'))
        batch_op.drop_index(batch_op.f('ix_professors_email'))

    op.drop_table('professors')
    with op.batch_alter_table('course_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_templates_id'))
        batch_op.drop_index(batch_op.f('ix_course_templates_code'))

    op.drop_table('course_templates')
    with op.batch_alter_table('constraints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_constraints_id'))

    op.drop_table('constraints')
    # ### end Alembic commands ###
